import type { McqQuestion } from './types';

export const QUESTION_CATEGORIES = [
  'Mathematics',
  'Science',
  'History',
  'Geography',
  'English',
  'General Knowledge',
] as const;

export const SAMPLE_QUESTIONS: McqQuestion[] = [
  {
    id: 'm1',
    category: 'Mathematics',
    question: 'What is 15 + 27?',
    options: ['40', '41', '42', '43'],
    correctIndex: 2,
    difficulty: 'easy',
    explanation: '15 + 27 = 42',
  },
  {
    id: 'm2',
    category: 'Mathematics',
    question: 'What is the square root of 144?',
    options: ['10', '11', '12', '13'],
    correctIndex: 2,
    difficulty: 'easy',
    explanation: '12 × 12 = 144',
  },
  {
    id: 'm3',
    category: 'Mathematics',
    question: 'Solve for x: 2x + 5 = 15',
    options: ['3', '4', '5', '6'],
    correctIndex: 2,
    difficulty: 'medium',
    explanation: '2x = 10, so x = 5',
  },
  {
    id: 'm4',
    category: 'Mathematics',
    question: 'What is 25% of 80?',
    options: ['15', '20', '25', '30'],
    correctIndex: 1,
    difficulty: 'medium',
    explanation: '25% of 80 = 0.25 × 80 = 20',
  },
  {
    id: 'm5',
    category: 'Mathematics',
    question: 'If f(x) = x² - 4x + 4, what is f(3)?',
    options: ['0', '1', '2', '3'],
    correctIndex: 1,
    difficulty: 'hard',
    explanation: 'f(3) = 9 - 12 + 4 = 1',
  },
  {
    id: 's1',
    category: 'Science',
    question: 'What is the chemical symbol for water?',
    options: ['H2O', 'CO2', 'O2', 'NaCl'],
    correctIndex: 0,
    difficulty: 'easy',
    explanation: 'Water is H2O - two hydrogen atoms and one oxygen',
  },
  {
    id: 's2',
    category: 'Science',
    question: 'Which planet is known as the Red Planet?',
    options: ['Venus', 'Mars', 'Jupiter', 'Saturn'],
    correctIndex: 1,
    difficulty: 'easy',
    explanation: 'Mars appears red due to iron oxide on its surface',
  },
  {
    id: 's3',
    category: 'Science',
    question: 'What is the powerhouse of the cell?',
    options: ['Nucleus', 'Ribosome', 'Mitochondria', 'Golgi apparatus'],
    correctIndex: 2,
    difficulty: 'medium',
    explanation: "Mitochondria produce ATP, the cell's energy currency",
  },
  {
    id: 's4',
    category: 'Science',
    question: 'At what temperature does water boil at sea level?',
    options: ['90°C', '100°C', '110°C', '120°C'],
    correctIndex: 1,
    difficulty: 'medium',
    explanation: 'Water boils at 100°C (212°F) at standard atmospheric pressure',
  },
  {
    id: 's5',
    category: 'Science',
    question: 'What is the speed of light in vacuum (approximately)?',
    options: ['299,792 km/s', '300,000 km/s', '299,792 m/s', '3 × 10⁸ m/s'],
    correctIndex: 0,
    difficulty: 'hard',
    explanation: 'The exact value is 299,792,458 m/s',
  },
  {
    id: 'h1',
    category: 'History',
    question: 'In which year did World War II end?',
    options: ['1943', '1944', '1945', '1946'],
    correctIndex: 2,
    difficulty: 'easy',
    explanation: "WWII ended in 1945 with Japan's surrender",
  },
  {
    id: 'h2',
    category: 'History',
    question: 'Who was the first President of the United States?',
    options: ['John Adams', 'Thomas Jefferson', 'George Washington', 'Benjamin Franklin'],
    correctIndex: 2,
    difficulty: 'easy',
    explanation: 'George Washington served from 1789-1797',
  },
  {
    id: 'h3',
    category: 'History',
    question: 'The Renaissance began in which country?',
    options: ['France', 'Germany', 'Italy', 'Spain'],
    correctIndex: 2,
    difficulty: 'medium',
    explanation: 'The Renaissance started in Italy in the 14th century',
  },
  {
    id: 'h4',
    category: 'History',
    question: 'When did the Berlin Wall fall?',
    options: ['1987', '1988', '1989', '1990'],
    correctIndex: 2,
    difficulty: 'medium',
    explanation: 'The Berlin Wall fell on November 9, 1989',
  },
  {
    id: 'h5',
    category: 'History',
    question: 'Who wrote "The Republic"?',
    options: ['Aristotle', 'Socrates', 'Plato', 'Pythagoras'],
    correctIndex: 2,
    difficulty: 'hard',
    explanation: 'Plato wrote "The Republic" around 380 BCE',
  },
  {
    id: 'g1',
    category: 'Geography',
    question: 'What is the capital of France?',
    options: ['Lyon', 'Marseille', 'Paris', 'Bordeaux'],
    correctIndex: 2,
    difficulty: 'easy',
    explanation: 'Paris is the capital and largest city of France',
  },
  {
    id: 'g2',
    category: 'Geography',
    question: 'Which is the largest ocean on Earth?',
    options: ['Atlantic', 'Indian', 'Arctic', 'Pacific'],
    correctIndex: 3,
    difficulty: 'easy',
    explanation: 'The Pacific Ocean covers about 63 million square miles',
  },
  {
    id: 'g3',
    category: 'Geography',
    question: 'Mount Everest is located in which mountain range?',
    options: ['Alps', 'Andes', 'Himalayas', 'Rockies'],
    correctIndex: 2,
    difficulty: 'medium',
    explanation: 'Mount Everest is in the Himalayas on the Nepal-China border',
  },
  {
    id: 'g4',
    category: 'Geography',
    question: 'Which country has the most time zones?',
    options: ['USA', 'Russia', 'France', 'China'],
    correctIndex: 2,
    difficulty: 'medium',
    explanation: 'France has 12 time zones due to its overseas territories',
  },
  {
    id: 'g5',
    category: 'Geography',
    question: 'The Tropic of Capricorn passes through which continent(s)?',
    options: [
      'Africa only',
      'South America only',
      'Australia only',
      'Africa, South America, Australia',
    ],
    correctIndex: 3,
    difficulty: 'hard',
    explanation: 'The Tropic of Capricorn crosses all three continents',
  },
  {
    id: 'e1',
    category: 'English',
    question: 'What is the past tense of "go"?',
    options: ['goed', 'went', 'gone', 'going'],
    correctIndex: 1,
    difficulty: 'easy',
    explanation: 'The irregular past tense of "go" is "went"',
  },
  {
    id: 'e2',
    category: 'English',
    question: 'Which word is a noun?',
    options: ['quickly', 'happiness', 'beautiful', 'run'],
    correctIndex: 1,
    difficulty: 'easy',
    explanation: 'Happiness is a noun (abstract noun)',
  },
  {
    id: 'e3',
    category: 'English',
    question: 'Identify the correct sentence.',
    options: [
      "She don't like coffee.",
      "She doesn't likes coffee.",
      "She doesn't like coffee.",
      'She not like coffee.',
    ],
    correctIndex: 2,
    difficulty: 'medium',
    explanation: 'Third person singular uses "doesn\'t" + base verb',
  },
  {
    id: 'e4',
    category: 'English',
    question: 'What is the plural of "phenomenon"?',
    options: ['phenomenons', 'phenomena', 'phenomenas', 'phenomenon'],
    correctIndex: 1,
    difficulty: 'medium',
    explanation: '"Phenomenon" has the irregular plural "phenomena"',
  },
  {
    id: 'e5',
    category: 'English',
    question: 'Which sentence uses the subjunctive mood correctly?',
    options: [
      'I suggest that he goes.',
      'I suggest that he go.',
      'I suggest him to go.',
      'I suggest he going.',
    ],
    correctIndex: 1,
    difficulty: 'hard',
    explanation: 'After "suggest that", we use the base form "go"',
  },
  {
    id: 'gk1',
    category: 'General Knowledge',
    question: 'How many continents are there?',
    options: ['5', '6', '7', '8'],
    correctIndex: 2,
    difficulty: 'easy',
    explanation:
      'There are 7 continents: Africa, Antarctica, Asia, Europe, North America, Oceania, South America',
  },
  {
    id: 'gk2',
    category: 'General Knowledge',
    question: 'What color is the sky on a clear day?',
    options: ['Green', 'Blue', 'White', 'Yellow'],
    correctIndex: 1,
    difficulty: 'easy',
    explanation: 'Rayleigh scattering makes the sky appear blue',
  },
  {
    id: 'gk3',
    category: 'General Knowledge',
    question: 'Who painted the Mona Lisa?',
    options: ['Michelangelo', 'Raphael', 'Leonardo da Vinci', 'Donatello'],
    correctIndex: 2,
    difficulty: 'medium',
    explanation: 'Leonardo da Vinci painted it in the early 16th century',
  },
  {
    id: 'gk4',
    category: 'General Knowledge',
    question: 'What is the smallest prime number?',
    options: ['0', '1', '2', '3'],
    correctIndex: 2,
    difficulty: 'medium',
    explanation: '2 is the smallest and only even prime number',
  },
  {
    id: 'gk5',
    category: 'General Knowledge',
    question: 'In which year was the first iPhone released?',
    options: ['2005', '2006', '2007', '2008'],
    correctIndex: 2,
    difficulty: 'hard',
    explanation: 'Steve Jobs unveiled the first iPhone on January 9, 2007',
  },
];

export function getQuestionsByCategoryAndDifficulty(
  category: string,
  difficulty: string,
  excludeIds: string[] = []
): McqQuestion[] {
  return SAMPLE_QUESTIONS.filter(
    (q) => q.category === category && q.difficulty === difficulty && !excludeIds.includes(q.id)
  );
}

export function getQuestionById(id: string): McqQuestion | undefined {
  return SAMPLE_QUESTIONS.find((q) => q.id === id);
}
